### PR TITLE
Fix Qt JIT error under hardened SELinux policies

### LINKED ISSUE #66: Krita from Flatpak does not start (RHEL/CentOS 9)
STEPS TO REPRODUCE
1. install krita over flatpak (ignoring gpg issues)
2. flatpak run org.kde.krita
3. failure

OBSERVED RESULT
[root@magnesiumtoaster ~]# flatpak run org.kde.krita
QObject::startTimer: Timers cannot have negative intervals
/app/lib/krita-python-libs/krita added to PYTHONPATH
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
*** stack smashing detected ***: terminated

EXPECTED RESULT
that krita would start

SOFTWARE/OS VERSIONS
Windows: 
macOS: 
Linux/KDE Plasma: Centos Stream 9/ RHEL 9, full latest updates
(available in About System)
KDE Plasma Version: ? have not manually intervened
KDE Frameworks Version: ? have not manually intervened
Qt Version: ? have not manually intervened

ADDITIONAL INFORMATION

Have tried user install, root install, restarts inbetween, still ending up with the same fail.
Splash screen pops up, crash right after that.

### PR DESCRIPTION
**Pull request by vulongm**
Included patches from Krita devs https://invent.kde.org/graphics/krita/-/merge_requests/1592 to try and resolve #66

### CODE REVIEW

**Comment by travier** [comment]
@David-Else @Talispaehn Can you try this build to confirm it's fixed?

**Comment by vulongm** [comment]
> I tested the new test version, Krita starts and I can use it! Thanks :)

Good to hear it works now! Since it's finalized upstream as well, I merged it into the stable branch so it should be live on flathub in a few hours.

> Ages ago I used the nextcloud appimage and it didn't work, I since remove it. It seems to have left something in my system which is causing this whenever I start Krita... any idea what is going on?

That's strange, I wonder if the nextcloud appimage added any startup scripts. Does the error occur on other Qt apps as well such as another KDE app that uses Qt5?

**Comment by David-Else** [comment]
@vulongm I removed the test version and installed the full flathub version, and all is well now :) Thanks again for this quick fix.

Reg the nextcloud problem, I have asked for help on a forum and will report back here with my results. I don't think I have any other Qt5 apps.

**Comment by travier** [comment]
The SELinux error you've linked above is the mprotect one that should be fixed here. The issue you're seeing is likely unrelated.

**Pull request merged**
