### PR TITLE
krita 4.3.0

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by eszlari** [comment]
I tested the build, the file open dialog doesn't show up under Plasma.

@grulja Can you reproduce this?

**Comment by grulja** [comment]
I haven't tried, but my first guess is:
https://github.com/flathub/flathub/pull/1583#issuecomment-644549140

You can verify it by running "dbus-monitor --session".

**Comment by eszlari** [comment]
```
method call time=1592565901.490765 sender=:1.54 -> destination=org.freedesktop.portal.Desktop serial=36 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=OpenFile
   string "x11:92274715"
   string "Open Images"
   array [
      dict entry(
         string "filters"
         variant             array [
               struct {
                  string "All supported formats "
                  array [
                     struct {
                        uint32 0
                        string "*.pdf"
                     }
                     struct {
                        uint32 0
                        string "*.exr"
                     }
                     struct {
                        uint32 0
                        string "*.kra"
                     }
                     struct {
                        uint32 0
                        string "*.kpp"
                     }
                     struct {
                        uint32 0
                        string "*.bmp"
                     }
                     struct {
                        uint32 0
                        string "*.dib"
                     }
                     struct {
                        uint32 0
                        string "*.gif"
                     }
                     struct {
                        uint32 0
                        string "*.jpg"
                     }
                     struct {
                        uint32 0
                        string "*.jpeg"
                     }
                     struct {
                        uint32 0
                        string "*.jpe"
                     }
                     struct {
                        uint32 0
                        string "*.ora"
                     }
                     struct {
                        uint32 0
                        string "*.psd"
                     }
                     struct {
                        uint32 0
                        string "*.png"
                     }
                     struct {
                        uint32 0
                        string "*.svg"
                     }
                     struct {
                        uint32 0
                        string "*.tif"
                     }
                     struct {
                        uint32 0
                        string "*.tiff"
                     }
                     struct {
                        uint32 0
                        string "*.psd"
                     }
                     struct {
                        uint32 0
                        string "*.ico"
                     }
                     struct {
                        uint32 0
                        string "*.webp"
                     }
                     struct {
                        uint32 0
                        string "*.exr"
                     }
                     struct {
                        uint32 0
                        string "*.gbr"
                     }
                     struct {
                        uint32 0
                        string "*.vbr"
                     }
                     struct {
                        uint32 0
                        string "*.gih"
                     }
                     struct {
                        uint32 0
                        string "*.bay"
                     }
                     struct {
                        uint32 0
                        string "*.bmq"
                     }
                     struct {
                        uint32 0
                        string "*.cr2"
                     }
                     struct {
                        uint32 0
                        string "*.crw"
                     }
                     struct {
                        uint32 0
                        string "*.cs1"
                     }
                     struct {
                        uint32 0
                        string "*.dc2"
                     }
                     struct {
                        uint32 0
                        string "*.dcr"
                     }
                     struct {
                        uint32 0
                        string "*.dng"
                     }
                     struct {
                        uint32 0
                        string "*.erf"
                     }
                     struct {
                        uint32 0
                        string "*.fff"
                     }
                     struct {
                        uint32 0
                        string "*.hdr"
                     }
                     struct {
                        uint32 0
                        string "*.k25"
                     }
                     struct {
                        uint32 0
                        string "*.kdc"
                     }
                     struct {
                        uint32 0
                        string "*.mdc"
                     }
                     struct {
                        uint32 0
                        string "*.mos"
                     }
                     struct {
                        uint32 0
                        string "*.mrw"
                     }
                     struct {
                        uint32 0
                        string "*.nef"
                     }
                     struct {
                        uint32 0
                        string "*.orf"
                     }
                     struct {
                        uint32 0
                        string "*.pef"
                     }
                     struct {
                        uint32 0
                        string "*.pxn"
                     }
                     struct {
                        uint32 0
                        string "*.raf"
                     }
                     struct {
                        uint32 0
                        string "*.raw"
                     }
                     struct {
                        uint32 0
                        string "*.rdc"
                     }
                     struct {
                        uint32 0
                        string "*.sr2"
                     }
                     struct {
                        uint32 0
                        string "*.srf"
                     }
                     struct {
                        uint32 0
                        string "*.x3f"
                     }
                     struct {
                        uint32 0
                        string "*.arw"
                     }
                     struct {
                        uint32 0
                        string "*.3fr"
                     }
                     struct {
                        uint32 0
                        string "*.cine"
                     }
                     struct {
                        uint32 0
                        string "*.ia"
                     }
                     struct {
                        uint32 0
                        string "*.kc2"
                     }
                     struct {
                        uint32 0
                        string "*.mef"
                     }
                     struct {
                        uint32 0
                        string "*.nrw"
                     }
                     struct {
                        uint32 0
                        string "*.qtk"
                     }
                     struct {
                        uint32 0
                        string "*.rw2"
                     }
                     struct {
                        uint32 0
                        string "*.sti"
                     }
                     struct {
                        uint32 0
                        string "*.rwl"
                     }
                     struct {
                        uint32 0
                        string "*.srw"
                     }
                     struct {
                        uint32 0
                        string "*.psd"
                     }
                     struct {
                        uint32 0
                        string "*.pbm"
                     }
                     struct {
                        uint32 0
                        string "*.pgm"
                     }
                     struct {
                        uint32 0
                        string "*.ppm"
                     }
                     struct {
                        uint32 0
                        string "*.psb"
                     }
                     struct {
                        uint32 0
                        string "*.psd"
                     }
                     struct {
                        uint32 0
                        string "*.r16"
                     }
                     struct {
                        uint32 0
                        string "*.r32"
                     }
                     struct {
                        uint32 0
                        string "*.r8"
                     }
                     struct {
                        uint32 0
                        string "*.tga"
                     }
                     struct {
                        uint32 0
                        string "*.icb"
                     }
                     struct {
                        uint32 0
                        string "*.tpic"
                     }
                     struct {
                        uint32 0
                        string "*.vda"
                     }
                     struct {
                        uint32 0
                        string "*.vst"
                     }
                     struct {
                        uint32 0
                        string "*.xbm"
                     }
                     struct {
                        uint32 0
                        string "*.xcf"
                     }
                     struct {
                        uint32 0
                        string "*.xpm"
                     }
                     struct {
                        uint32 0
                        string "*.csv"
                     }
                  ]
               }
               struct {
                  string "Krita document "
                  array [
                     struct {
                        uint32 0
                        string "*.kra"
                     }
                  ]
               }
               struct {
                  string "OpenRaster Image "
                  array [
                     struct {
                        uint32 0
                        string "*.ora"
                     }
                  ]
               }
               struct {
                  string "CSV document "
                  array [
                     struct {
                        uint32 0
                        string "*.csv"
                     }
                  ]
               }
               struct {
                  string "Camera Raw Files "
                  array [
                     struct {
                        uint32 0
                        string "*.bay"
                     }
                     struct {
                        uint32 0
                        string "*.bmq"
                     }
                     struct {
                        uint32 0
                        string "*.cr2"
                     }
                     struct {
                        uint32 0
                        string "*.crw"
                     }
                     struct {
                        uint32 0
                        string "*.cs1"
                     }
                     struct {
                        uint32 0
                        string "*.dc2"
                     }
                     struct {
                        uint32 0
                        string "*.dcr"
                     }
                     struct {
                        uint32 0
                        string "*.dng"
                     }
                     struct {
                        uint32 0
                        string "*.erf"
                     }
                     struct {
                        uint32 0
                        string "*.fff"
                     }
                     struct {
                        uint32 0
                        string "*.hdr"
                     }
                     struct {
                        uint32 0
                        string "*.k25"
                     }
                     struct {
                        uint32 0
                        string "*.kdc"
                     }
                     struct {
                        uint32 0
                        string "*.mdc"
                     }
                     struct {
                        uint32 0
                        string "*.mos"
                     }
                     struct {
                        uint32 0
                        string "*.mrw"
                     }
                     struct {
                        uint32 0
                        string "*.nef"
                     }
                     struct {
                        uint32 0
                        string "*.orf"
                     }
                     struct {
                        uint32 0
                        string "*.pef"
                     }
                     struct {
                        uint32 0
                        string "*.pxn"
                     }
                     struct {
                        uint32 0
                        string "*.raf"
                     }
                     struct {
                        uint32 0
                        string "*.raw"
                     }
                     struct {
                        uint32 0
                        string "*.rdc"
                     }
                     struct {
                        uint32 0
                        string "*.sr2"
                     }
                     struct {
                        uint32 0
                        string "*.srf"
                     }
                     struct {
                        uint32 0
                        string "*.x3f"
                     }
                     struct {
                        uint32 0
                        string "*.arw"
                     }
                     struct {
                        uint32 0
                        string "*.3fr"
                     }
                     struct {
                        uint32 0
                        string "*.cine"
                     }
                     struct {
                        uint32 0
                        string "*.ia"
                     }
                     struct {
                        uint32 0
                        string "*.kc2"
                     }
                     struct {
                        uint32 0
                        string "*.mef"
                     }
                     struct {
                        uint32 0
                        string "*.nrw"
                     }
                     struct {
                        uint32 0
                        string "*.qtk"
                     }
                     struct {
                        uint32 0
                        string "*.rw2"
                     }
                     struct {
                        uint32 0
                        string "*.sti"
                     }
                     struct {
                        uint32 0
                        string "*.rwl"
                     }
                     struct {
                        uint32 0
                        string "*.srw"
                     }
                  ]
               }
               struct {
                  string "EXR image "
                  array [
                     struct {
                        uint32 0
                        string "*.exr"
                     }
                  ]
               }
               struct {
                  string "GIF image "
                  array [
                     struct {
                        uint32 0
                        string "*.gif"
                     }
                  ]
               }
               struct {
                  string "GIMP image "
                  array [
                     struct {
                        uint32 0
                        string "*.xcf"
                     }
                  ]
               }
               struct {
                  string "Gimp Brush "
                  array [
                     struct {
                        uint32 0
                        string "*.gbr"
                     }
                     struct {
                        uint32 0
                        string "*.vbr"
                     }
                  ]
               }
               struct {
                  string "Gimp Image Hose Brush "
                  array [
                     struct {
                        uint32 0
                        string "*.gih"
                     }
                  ]
               }
               struct {
                  string "JPEG image "
                  array [
                     struct {
                        uint32 0
                        string "*.jpg"
                     }
                     struct {
                        uint32 0
                        string "*.jpeg"
                     }
                     struct {
                        uint32 0
                        string "*.jpe"
                     }
                  ]
               }
               struct {
                  string "Krita Brush Preset "
                  array [
                     struct {
                        uint32 0
                        string "*.kpp"
                     }
                  ]
               }
               struct {
                  string "OpenEXR (Extended) "
                  array [
                     struct {
                        uint32 0
                        string "*.exr"
                     }
                  ]
               }
               struct {
                  string "PBM image "
                  array [
                     struct {
                        uint32 0
                        string "*.pbm"
                     }
                  ]
               }
               struct {
                  string "PDF document "
                  array [
                     struct {
                        uint32 0
                        string "*.pdf"
                     }
                  ]
               }
               struct {
                  string "PGM image "
                  array [
                     struct {
                        uint32 0
                        string "*.pgm"
                     }
                  ]
               }
               struct {
                  string "PNG image "
                  array [
                     struct {
                        uint32 0
                        string "*.png"
                     }
                  ]
               }
               struct {
                  string "PPM image "
                  array [
                     struct {
                        uint32 0
                        string "*.ppm"
                     }
                  ]
               }
               struct {
                  string "Photoshop Image (Large) "
                  array [
                     struct {
                        uint32 0
                        string "*.psb"
                     }
                  ]
               }
               struct {
                  string "Photoshop image "
                  array [
                     struct {
                        uint32 0
                        string "*.psd"
                     }
                  ]
               }
               struct {
                  string "R16 Heightmap "
                  array [
                     struct {
                        uint32 0
                        string "*.r16"
                     }
                  ]
               }
               struct {
                  string "R32 Heightmap "
                  array [
                     struct {
                        uint32 0
                        string "*.r32"
                     }
                  ]
               }
               struct {
                  string "R8 Heightmap "
                  array [
                     struct {
                        uint32 0
                        string "*.r8"
                     }
                  ]
               }
               struct {
                  string "SVG image "
                  array [
                     struct {
                        uint32 0
                        string "*.svg"
                     }
                  ]
               }
               struct {
                  string "TGA image "
                  array [
                     struct {
                        uint32 0
                        string "*.tga"
                     }
                     struct {
                        uint32 0
                        string "*.icb"
                     }
                     struct {
                        uint32 0
                        string "*.tpic"
                     }
                     struct {
                        uint32 0
                        string "*.vda"
                     }
                     struct {
                        uint32 0
                        string "*.vst"
                     }
                  ]
               }
               struct {
                  string "TIFF image "
                  array [
                     struct {
                        uint32 0
                        string "*.tif"
                     }
                     struct {
                        uint32 0
                        string "*.tiff"
                     }
                  ]
               }
               struct {
                  string "WebP image "
                  array [
                     struct {
                        uint32 0
                        string "*.webp"
                     }
                  ]
               }
               struct {
                  string "Windows BMP image "
                  array [
                     struct {
                        uint32 0
                        string "*.bmp"
                     }
                     struct {
                        uint32 0
                        string "*.dib"
                     }
                  ]
               }
               struct {
                  string "Windows icon "
                  array [
                     struct {
                        uint32 0
                        string "*.ico"
                     }
                  ]
               }
               struct {
                  string "XBM image "
                  array [
                     struct {
                        uint32 0
                        string "*.xbm"
                     }
                  ]
               }
               struct {
                  string "XPM image "
                  array [
                     struct {
                        uint32 0
                        string "*.xpm"
                     }
                  ]
               }
               struct {
                  string "jfif "
                  array [
                  ]
               }
            ]
      )
      dict entry(
         string "handle_token"
         variant             string "qt276981311"
      )
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "multiple"
         variant             boolean true
      )
   ]
error time=1592565901.492377 sender=:1.45 -> destination=:1.54 error_name=org.freedesktop.portal.Error.InvalidArgument reply_serial=36
   string "invalid filter: no filters"
```

**Comment by eszlari** [comment]
It works under GNOME, because Krita doesn't use the portal there.

**Comment by grulja** [comment]
This seems to be an issue in Krita, where the filter is:
`"jfif ( )"`
which is obviously not valid and therefore rejected by xdg-desktop-portal.

**Comment by boudewijnrempt** [comment]
Maybe this patch will help? https://invent.kde.org/graphics/krita/commit/38579ee967383ae662c3fb2b3e981ae1019b1745

**Comment by eszlari** [comment]
The patch works!

**Comment by boudewijnrempt** [comment]
Ah, cool! I wonder where I got the information from that jfif is a sub-type of image/jpeg, because I couldn't find it again.

**Pull request merged**
