### PR TITLE
Update G'MIC to 3.1.2

### PR DESCRIPTION
**Pull request by vulongm**

### CODE REVIEW

**Comment by vulongm** [comment]
```
[104/104] Linking CXX shared module krita_gmic_qt.so
FAILED: krita_gmic_qt.so 
: && /usr/bin/c++ -fPIC -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -fopenmp  -g -DNDEBUG -O2  -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--stack,16777216 -shared  -o krita_gmic_qt.so CMakeFiles/krita_gmic_qt.dir/krita_gmic_qt_autogen/mocs_compilation.cpp.o CMakeFiles/krita_gmic_qt.dir/src/ClickableLabel.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Common.cpp.o CMakeFiles/krita_gmic_qt.dir/src/OverrideCursor.cpp.o CMakeFiles/krita_gmic_qt.dir/src/DialogSettings.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/AbstractParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/BoolParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/ButtonParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/ChoiceParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/ColorParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/ConstParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/CustomDoubleSpinBox.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/CustomSpinBox.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/FileParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/FilterParametersWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/FloatParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/FolderParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/IntParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/LinkParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/MultilineTextParameterWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/NoteParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/PointParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/SeparatorParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterParameters/TextParameter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersModel.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersModelReader.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersPresenter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/FiltersView.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/TreeView.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersVisibilityMap.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FilterTagMap.cpp.o CMakeFiles/krita_gmic_qt.dir/src/CroppedImageListProxy.cpp.o CMakeFiles/krita_gmic_qt.dir/src/CroppedActiveLayerProxy.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSyncRunner.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterThread.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterTextTranslator.cpp.o CMakeFiles/krita_gmic_qt.dir/src/GmicQt.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Globals.cpp.o CMakeFiles/krita_gmic_qt.dir/src/GmicStdlib.cpp.o CMakeFiles/krita_gmic_qt.dir/src/GmicProcessor.cpp.o CMakeFiles/krita_gmic_qt.dir/src/HeadlessProcessor.cpp.o CMakeFiles/krita_gmic_qt.dir/src/HtmlTranslator.cpp.o CMakeFiles/krita_gmic_qt.dir/src/IconLoader.cpp.o CMakeFiles/krita_gmic_qt.dir/src/ImageTools.cpp.o CMakeFiles/krita_gmic_qt.dir/src/InputOutputState.cpp.o CMakeFiles/krita_gmic_qt.dir/src/KeypointList.cpp.o CMakeFiles/krita_gmic_qt.dir/src/LayersExtentProxy.cpp.o CMakeFiles/krita_gmic_qt.dir/src/LanguageSettings.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Logger.cpp.o CMakeFiles/krita_gmic_qt.dir/src/MainWindow.cpp.o CMakeFiles/krita_gmic_qt.dir/src/ParametersCache.cpp.o CMakeFiles/krita_gmic_qt.dir/src/TimeLogger.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Tags.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Updater.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Utils.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Misc.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/FilterTreeItem.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/FilterTreeFolder.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FavesModel.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FavesModelReader.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/FilterTreeAbstractItem.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FiltersView/FilterTreeItemDelegate.cpp.o CMakeFiles/krita_gmic_qt.dir/src/FilterSelector/FavesModelWriter.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/PreviewWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/ProgressInfoWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/InOutPanel.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/ZoomLevelSelector.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/SearchFieldWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/LanguageSelectionWidget.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/ProgressInfoWindow.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Widgets/VisibleTagSelector.cpp.o CMakeFiles/krita_gmic_qt.dir/run/build/gmic/src/gmic.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Host/KritaPlugin/host.cpp.o CMakeFiles/krita_gmic_qt.dir/src/Host/KritaPlugin/gmicqttoolplugin.cpp.o CMakeFiles/krita_gmic_qt.dir/krita_gmic_qt_autogen/EWIEGA46WW/qrc_gmic_qt.cpp.o CMakeFiles/krita_gmic_qt.dir/krita_gmic_qt_autogen/EWIEGA46WW/qrc_translations.cpp.o  -Wl,-rpath,"\$ORIGIN/"  /app/lib/libQt5Widgets.so.5.12.12  /app/lib/libQt5Gui.so.5.12.12  /app/lib/libQt5Network.so.5.12.12  /usr/lib/x86_64-linux-gnu/libpng.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libfftw3.so  /usr/lib/x86_64-linux-gnu/libfftw3_threads.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libfftw3_threads.so  /usr/lib/x86_64-linux-gnu/libcurl.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXext.so  /app/lib/libkritaqmicinterface.so  /app/lib/libKF5CoreAddons.so.5.76.0  /usr/lib/x86_64-linux-gnu/libfftw3.so  /usr/lib/x86_64-linux-gnu/libcurl.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXext.so  /app/lib/libkritaqmicinterface.so  /app/lib/libQt5Core.so.5.12.12 && :
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: unrecognized option '--stack'
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FB: host_command_exited_cb 1311385 256
]2;flatpak-builder: Cleanup gmicError: module gmic: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-1/build/.flatpak-builder/rofiles/rofiles-Bcdvfj
dbus-daemon[501223]: Reloaded configuration
```

@travier Do you happen to know what is causing the build here to fail? "unrecognized option '--stack'" stands out from the logs but I'm not sure if that's something on the flathub builders's end or if we can work around that.

**Comment by travier** [comment]
Sorry, it don't really know. Google gives me the following links that appear to be relevant:
- https://bugzilla.redhat.com/show_bug.cgi?id=86451
- https://stackoverflow.com/questions/60876158/setting-stack-size-in-cmake-with-gcc

**Comment by travier** [comment]
Ping me when it works for you. You might want to add flatpak external data checker configs to those dependencies to get them updated automatically.

**Comment by travier** [comment]
And we should probably ask for you to be made a maintainer of this app too.

**Comment by vulongm** [comment]
> Ping me when it works for you. You might want to add flatpak external data checker configs to those dependencies to get them updated automatically.

@travier Works here, I can add the f-e-d-c in another PR for all the dependencies.

> And we should probably ask for you to be made a maintainer of this app too.

Is there a procedure to go about applying for that?

**Comment by travier** [comment]
> @travier Works here, I can add the f-e-d-c in another PR for all the dependencies.
> 
> > And we should probably ask for you to be made a maintainer of this app too.
> 
> Is there a procedure to go about applying for that?

I've submitted this: https://github.com/flathub/flathub/issues/3223

Ping me there if you don't get an answer after 1/2 weeks.

**Pull request merged**
