### PR TITLE
Krita 4.4.8

### PR DESCRIPTION
**Pull request by vulongm**

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
Why is this not merged yet?

**Comment by travier** [comment]
Re-pushed to trigger a new build. Can you test it once it is completed? @Doomsdayrs ?

**Comment by Doomsdayrs** [comment]
@travier seems to fail at building

**Comment by vulongm** [comment]
bot, build

**Comment by Lunarequest** [comment]
I can confirm this pr works, it can be merged

**Comment by travier** [comment]
Great! Gentle ping to @eszlari @nedrichards @grulja

**Comment by vulongm** [comment]
@travier Any updates on if this is mergable?

**Comment by travier** [comment]
Looks like I have merge powers here so I just did it :)

**Comment by vulongm** [comment]
@travier Looks like for some reason the build is failing to download a dependency similar to one of the failed builds in this PR before. Is there a way to retry the build?
> Failed to download sources: module kwidgetsaddons: Error in the HTTP2 framing layer

**Comment by travier** [comment]
I don't have the access to do that. @nedrichards @barthalion maybe? Thanks

**Comment by travier** [comment]
I merged https://github.com/flathub/org.kde.krita/pull/46 which is a NOP code wise but should trigger a rebuild.

**Comment by vulongm** [comment]
@travier Hmm, I do see a similar error this time for one of the builds but different dependency.

**Pull request merged**
