### PR TITLE
bundle Qt

### LINKED ISSUE #25: Tablet offset in HiDPI mode caused by wrong version of Qt (5.14.2)
The flatpak package ships wrong version of Qt. Krita officially supports Qt 5.12.9 only and it needs these 6 custom patches applied to Qt:

0012-Synthesize-Enter-LeaveEvent-for-accepted-QTabletEven.patch
0013-Poison-Qt-s-headers-with-a-mark-about-presence-of-En.patch
0081-Fix-no-warning-for-overwriting-files-in-non-native-d.patch
0082-Make-jp-e-g-default-extensions-context-aware.patch
0100-Fix-artifacts-when-rendering-multisubpath-dashed-QPa.patch
0101-Don-t-eat-ShortcutOverride-events-when-there-is-a-pa.patch
0110-Pass-proper-dirty-rect-in-paint-event-to-QOpenGLWidg.patch

Download link: https://invent.kde.org/graphics/krita/-/tree/master/3rdparty/ext_qt

Right now the flatpak package is not usable on HiPDI displays because of this bug caused by a regression in Qt. Setting the proposed environment variable as a workaround makes the lines dizzy.

Krita bugreport:
https://bugs.kde.org/show_bug.cgi?id=427039

Related Qt bugreport (I guess the fix to it caused a regressions actually):
https://bugreports.qt.io/browse/QTBUG-77826

### PR DESCRIPTION
**Pull request by eszlari**
closes #25

### CODE REVIEW

**Comment by dimula73** [comment]
Could you help me with testing this package?

```
> flatpak install --user https://dl.flathub.org/build-repo/28379/org.kde.krita.flatpakref
error: The application org.kde.krita/x86_64/test requires the runtime org.freedesktop.Platform/x86_64/20.08 which was not found
```

Should I add more remotes?

```
> flatpak remotes
Name                 Options          
flathub              system           
org.kde.krita-origin user,no-enumerate
```

**Comment by cho2** [comment]
@dimula73 please try
```
flatpak install --user flathub org.freedesktoorg.freedesktop.Platform//20.08
flatpak install --user https://dl.flathub.org/build-repo/28379/org.kde.krita.flatpakref
```

**Comment by dimula73** [comment]
The original bug seem to be fixed in this package. Though there are two issues:

1) [minor] With this change there is not 'breeze' support built it. It is officially not supported by Krita (due to bugs), but with previous packaging type people could override it with `QT_STYLE_OVERRIDE`. Since it has never been officially supported we can just ignore that :)

2) [blocking] For some reason Krita has Preferences->Global->Miscellaneous->"Enable native file dialogs" enabled by default. It makes File->Open menu action do nothing. Even though in normal Krita build this option is disabled by this code:
    ```
    if (qgetenv("XDG_CURRENT_DESKTOP") == "KDE") {
        dontUseNative = false;
    }
    ```  
   NOTE: in the previous builds this option has also bee enabled, but KDE's file dialogs worked fine. Now they don't.

**Comment by dimula73** [comment]
Btw, thank you for your help, @cho2! The problem was in `--user` switch. It seem to have blocked access to the system-wide flathub repository.

**Comment by eszlari** [comment]
https://bugs.kde.org/show_bug.cgi?id=427390


> It seem to have blocked access to the system-wide flathub repository.

--system and --user installations are always separate

**Comment by tsdgeos** [comment]
>     2. [blocking] For some reason Krita has Preferences->Global->Miscellaneous->"Enable native file dialogs" enabled by default. It makes File->Open menu action do nothing. Even though in normal Krita build this option is disabled by this code:
>        ```
>        if (qgetenv("XDG_CURRENT_DESKTOP") == "KDE") {
>            dontUseNative = false;
>        }
>        ```

You don't get a dialog in process with flatpak, you ask for a file and the file portal takes care of showing the dialog and giving you back a a file.

For some reason the portal is not liking the request this krita is making, see http://paste.debian.net/1166148/

I wonder if maybe the Qt 5.12 portal doesn't know how to talk to a modern Plasma? @grulja any idea?

**Comment by grulja** [comment]
> > ```
> > 2. [blocking] For some reason Krita has Preferences->Global->Miscellaneous->"Enable native file dialogs" enabled by default. It makes File->Open menu action do nothing. Even though in normal Krita build this option is disabled by this code:
> >    ```
> >    if (qgetenv("XDG_CURRENT_DESKTOP") == "KDE") {
> >        dontUseNative = false;
> >    }
> >    ```
> > ```
> 
> You don't get a dialog in process with flatpak, you ask for a file and the file portal takes care of showing the dialog and giving you back a a file.
> 
> For some reason the portal is not liking the request this krita is making, see http://paste.debian.net/1166148/
> 
> I wonder if maybe the Qt 5.12 portal doesn't know how to talk to a modern Plasma? @grulja any idea?

This is because Krita sends an empty filter.

It can be fixed on Krita side, but I submitted a fix to Qt: https://codereview.qt-project.org/c/qt/qtbase/+/316508

**Comment by dimula73** [comment]
Can it be that ` image/jp2` mimetype is not available on the flatpak image for some reason? It looks as if the json section for jp2 file format is generated from a wrongly split string.

**Comment by tsdgeos** [comment]
@eszlari can you add Jan's patch to the patches of Qt used for this?

**Comment by dimula73** [comment]
Hi, @eszlari!

The new package seem to work fine :) I could only find one problem: there are very few application languages available, but that is not a regression. Languages are also not available in the old package.

**Comment by Siosm** [comment]
> I could only find one problem: there are very few application languages available, but that is not a regression. Languages are also not available in the old package.

Can you file that as another issue so that it can be properly investigated? Thanks

**Comment by dimula73** [comment]
Hi, @Siosm!

> Can you file that as another issue so that it can be properly investigated? Thanks

Done: https://github.com/flathub/org.kde.krita/issues/27

PS:
This MR looks to work correctly

**Comment by tsdgeos** [comment]
Ok, so i'd say merge this?

Let's  hope Krita's technical debt doesn't become unsurmountable in the future.

**Pull request merged**
